global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'youtube-party'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics' 