groups:
  - name: youtube-party-alerts
    rules:
      # High error rate alert
      - alert: HighErrorRate
        expr: rate(youtube_party_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 10% for the last 5 minutes

      # Room capacity alert
      - alert: RoomCapacityHigh
        expr: youtube_party_active_rooms > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: High number of active rooms
          description: More than 100 active rooms for over 10 minutes

      # WebSocket latency alert
      - alert: HighWebSocketLatency
        expr: histogram_quantile(0.95, rate(youtube_party_ws_latency_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High WebSocket latency
          description: 95th percentile WebSocket latency is above 1 second

      # Queue operation failures
      - alert: QueueOperationFailures
        expr: increase(youtube_party_queue_operations_total{operation="error"}[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High queue operation failure rate
          description: More than 10 queue operation failures in 5 minutes

      # System health alerts
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 1024  # > 1GB
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Memory usage is above 1GB for 5 minutes

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: CPU usage is above 80% for 5 minutes

      # Application alerts
      - alert: APIHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler!="metrics"}[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High API response time
          description: 95th percentile of API response time is above 500ms

      - alert: HighRedisLatency
        expr: rate(redis_command_duration_seconds_sum[1m]) / rate(redis_command_duration_seconds_count[1m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Redis latency
          description: Average Redis command latency is above 100ms

      # Business metrics alerts
      - alert: LowUserActivity
        expr: rate(youtube_party_connected_users[15m]) < 1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Low user activity
          description: User connection rate has dropped below normal levels

      - alert: QueueProcessingDelay
        expr: youtube_party_queue_processing_delay_seconds > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Queue processing delay
          description: Queue items are taking more than 30 seconds to process

      # Worker alerts
      - alert: WorkerQueueBacklog
        expr: youtube_party_queue_length > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High queue backlog
          description: Queue length has been above 100 items for 5 minutes

      - alert: WorkerHighErrorRate
        expr: rate(youtube_party_queue_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High worker error rate
          description: Worker error rate is above 10% for 5 minutes

      - alert: WorkerHighProcessingTime
        expr: histogram_quantile(0.95, rate(youtube_party_queue_processing_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow queue processing
          description: 95th percentile of queue processing time is above 5 seconds

      - alert: NoActiveWorkers
        expr: youtube_party_active_workers == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: No active workers
          description: No worker processes are currently active

      # Worker coordination alerts
      - alert: WorkerHeartbeatMissing
        expr: time() - youtube_party_worker_heartbeat_timestamp > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Worker heartbeat missing
          description: Worker {{ $labels.worker_id }} has not sent a heartbeat in over 60 seconds

      - alert: WorkerLoadImbalance
        expr: |
          max(youtube_party_worker_load) by (worker_id)
          / 
          min(youtube_party_worker_load) by (worker_id)
          > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Worker load imbalance detected
          description: Load distribution between workers is uneven

      - alert: WorkerCoordinationFailure
        expr: sum(youtube_party_worker_coordination_info) by (status) == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Worker coordination failure
          description: No workers in active status

      - alert: HighWorkToWorkerRatio
        expr: histogram_quantile(0.95, rate(youtube_party_work_distribution_ratio_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High work to worker ratio
          description: Too many work items per worker, consider scaling up 