apiVersion: 1

notifiers:
  - name: Email
    type: email
    uid: email
    org_id: 1
    is_default: true
    settings:
      addresses: alerts@yourdomain.com

  - name: Slack
    type: slack
    uid: slack
    org_id: 1
    settings:
      url: ${SLACK_WEBHOOK_URL}
      recipient: "#alerts" 